spring.application.name=server
spring.datasource.url=jdbc:postgresql://${twin_database_host:localhost}:${twin_database_port:5432}/${twin_database_name:twinSport}
spring.datasource.username=${twin_database_username:postgres}
spring.datasource.password=${twin_database_password:ahmed123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Keep the connection alive if idle for a long time (needed in production)
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
app.cors.allowed-origins=${twin_allowed_origins:http://localhost:*/}
server.port=${SERVER_PORT:9000}
server.servlet.context-path=/twin-sport
#spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
jwt.secret=436750f4dbcbea824a1cddd28a2942e3476e65baea75de213fb85eec0b7e14f9254fd642d80131da918466096045206eb7ba83908db82ffcc17c26208ebaf8bfcfedf523ceeea17ba4c5b759febc14ad3619990d39060d9f0c0e558e683f6775ac57abed04f2d8e88e045fbd715a5f9cb6f7b144fd85ebf917394345bbe1dafae31867976aee96c4c8c70ec409f8a167ffc9f5ef25c79adb5d2bbca6abc501f60b3a38a3dafb85b454655e83ecf41b325ee6b0fbc75ecf29cd4c9497a3f63b1c7a03f598da0ad4625c184a7bd0d67ebff095f993431d5d1d51abecb5a6cfcd1ddb1f92d11e425b535a961413f39e4f364038abef9a4349d01a6fc1240fa41579
jwt.secret.utils=a52403dda6e5d24778232230b9426de3
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
app.upload.image-dir=${APP_UPLOAD_IMAGE_DIR:./img}
jwt.expiration.computer=36000000
jwt.expiration.mobile=28800000
jwt.expiration.reservation=900000
# SMTP Server (example: Gmail)
app.security.verification2FaDuration=12
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ahmedsiala765@gmail.com
spring.mail.password=eiav cwlh kdzo rtxf
app.security.cookieName=JMX-TOKEN
# Protocol
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional (debug)
spring.mail.properties.mail.debug=true